//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class admindetail
    {
        public int id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string password { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string Address { get; set; }
        public string userole { get; set; }
    }
}
