//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class userregistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userregistration()
        {
            this.bookvenues = new HashSet<bookvenue>();
        }
    
        public int id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string password { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookvenue> bookvenues { get; set; }
    }
}
